org: tomasalonz55
app: hibp
service: hibp

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  timeout: 120

functions:
  api:
    handler: handler.handler
    environment:
      API_KEY: ${param:API_KEY}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
